hl.on("hyprland.start", function()
	hl.exec_cmd("antimicrox --hidden --profile /home/gamepad_profiles/desktop-mode.gamecontroller.amgp")
	hl.exec_cmd("swaybg -i /home/haziel/background.jpg -m fill")
	-- hl.exec_cmd("awww-daemon")
	-- hl.exec_cmd("awww image /home/haziel/background.jpg --transition-type none")
	-- hl.exec_cmd("waydroid session start")
	hl.exec_cmd("env QT_QUICK_BACKEND=software skwd")
	-- hl.exec_cmd("/usr/share/skwd/scripts/bash/restore-wallpaper")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("udiskie --tray")
end)
