exec-once = antimicrox --hidden --profile /home/gamepad_profiles/desktop-mode.gamecontroller.amgp
# Wallpapers
exec-once = awww-daemon
exec-once = awww image /home/haziel/background.jpg --transition-type none
# Start skwd shell
exec-once = skwd
# Restore last wallpaper on startup
exec-once = /usr/share/skwd/scripts/bash/restore-wallpaper
