general {
   gaps_in = 0
   gaps_out = 0
}

decoration {
  rounding = 0
  active_opacity = 0.8
  inactive_opacity = 0.8
  blur {
    enabled = true
    ignore_opacity = true
    size = 8
    passes = 2
    new_optimizations = yes
  }
}

# Specific windows
windowrule = match:class firefox, opacity 1.5 0.8
